import { FileText, ClipboardList, Briefcase, Activity, CheckCircle2 } from "lucide-react"

export const DATA = {
  overview: {
    totalEnquiries: 1521,
    wonEnquiries: 145,
    activeJobs: 712,
    fclContainers: 1064,
    totalUnits: 8200,
    seaMBL: 405,
    airHAWB: 65,
    roadJobs: 13,
    podCompleted: 39,
  },
  enquiryStatus: [
    { name: "New", value: 1276, color: "#3b82f6" },
    { name: "Won", value: 145, color: "#16a34a" },
    { name: "Quoted", value: 96, color: "#a855f7" },
    { name: "Awaiting Rates", value: 4, color: "#f97316" },
  ],
  modeBreakdown: [
    { mode: "Sea", enquiries: 1110, jobs: 462 },
    { mode: "Air", enquiries: 306, jobs: 156 },
    { mode: "Road", enquiries: 104, jobs: 62 },
  ],
  subEnquirySea: [
    { direction: "Import", count: 612 },
    { direction: "Export", count: 398 },
    { direction: "Crosstrade", count: 100 },
  ],
  subEnquiryAir: [
    { direction: "Import", count: 168 },
    { direction: "Export", count: 102 },
    { direction: "Crosstrade", count: 36 },
  ],
  subEnquiryRoad: [
    { direction: "Import", count: 58 },
    { direction: "Export", count: 32 },
    { direction: "Clearance", count: 14 },
  ],
  jobBreakdown: [
    { label: "Sea Import", value: 251, mode: "sea" },
    { label: "Sea Export", value: 151, mode: "sea" },
    { label: "Air Import", value: 83, mode: "air" },
    { label: "Air Export", value: 48, mode: "air" },
    { label: "Sea Clearance", value: 36, mode: "sea" },
    { label: "Road Import", value: 33, mode: "road" },
    { label: "Air Crosstrade", value: 25, mode: "air" },
    { label: "Sea Crosstrade", value: 24, mode: "sea" },
    { label: "Road Export", value: 16, mode: "road" },
    { label: "Road Clearance", value: 13, mode: "road" },
  ],
  funnel: [
    { name: "Enquiries", value: 1521, fill: "#3b82f6" },
    { name: "Won", value: 145, fill: "#a855f7" },
    { name: "Jobs", value: 712, fill: "#16a34a" },
  ],
  containers: [
    { type: "20ft Std", count: 528, qty: 3280 },
    { type: "40ft Std", count: 167, qty: 3554 },
    { type: "40ft HC", count: 276, qty: 698 },
    { type: "20ft OT", count: 37, qty: 75 },
    { type: "45ft HC", count: 18, qty: 70 },
    { type: "40ft RF", count: 12, qty: 23 },
  ],
  customersByEnquiry: [
    { name: "Arteco Ceramics LLC", count: 44, initials: "AC" },
    { name: "Ghassan Ahmed Al Sulaiman", count: 31, initials: "GA" },
    { name: "Final Specs Flooring", count: 25, initials: "FS" },
    { name: "VOLTUSWAVE ORGANIZATION", count: 23, initials: "VO" },
  ],
  customersByJob: [
    { name: "Al Faiq Readymade Garments", count: 11, initials: "AF" },
    { name: "Arteco Ceramics LLC", count: 11, initials: "AC" },
    { name: "Sun & Sand Sports", count: 10, initials: "SS" },
  ],
  sparkline: [
    { d: 1, v: 42 }, { d: 2, v: 58 }, { d: 3, v: 51 },
    { d: 4, v: 72 }, { d: 5, v: 65 }, { d: 6, v: 84 },
    { d: 7, v: 79 }, { d: 8, v: 96 }, { d: 9, v: 88 }, { d: 10, v: 112 },
  ],
  recentPODs: [
    { id: "POD-2891", customer: "Arteco Ceramics", mode: "sea", location: "Jebel Ali", time: "2h ago", status: "Delivered" },
    { id: "POD-2890", customer: "Sun & Sand Sports", mode: "air", location: "DXB Cargo", time: "5h ago", status: "Delivered" },
    { id: "POD-2889", customer: "Al Faiq Garments", mode: "sea", location: "Mundra Port", time: "Yesterday", status: "Delivered" },
    { id: "POD-2888", customer: "Final Specs", mode: "road", location: "Riyadh DC", time: "Yesterday", status: "Delivered" },
    { id: "POD-2887", customer: "Ghassan Ahmed", mode: "sea", location: "Dammam", time: "2d ago", status: "Delivered" },
  ],
  paymentsDashboard: {
    invoices: {
      total: 261,
      rows: [
        { status: "sent", mode: "Sea", count: 2, grandTotalAed: 4016436764 },
        { status: "draft", mode: "Sea", count: 121, grandTotalAed: 1280442 },
        { status: "paid", mode: "Sea", count: 5, grandTotalAed: 67805 },
        { status: "draft", mode: "Road", count: 2, grandTotalAed: 48804 },
        { status: "draft", mode: "Air", count: 4, grandTotalAed: 29325 },
      ],
      outlierNote: "One very large sent invoice (likely test data — Aquajets Marine Equipment, AED 4B).",
    },
    paymentReceipts: {
      total: 46,
      status: "Draft",
      rows: [
        { currency: "AED", count: 42, received: 319347, allocated: 121007, unallocated: 198339 },
        { currency: "QAR", count: 3, received: 27688, allocated: 0, unallocated: 27688 },
        { currency: "USD", count: 1, received: 2946, allocated: 2946, unallocated: 0 },
      ],
    },
    paymentDisbursements: {
      total: 16,
      status: "Draft",
      totalAed: 39426,
    },
    purchaseOrders: {
      total: 172,
      rows: [
        { status: "sent", currency: "AED", count: 42, totalAmount: null },
        { status: "sent", currency: "USD", count: 29, totalAmount: 38569 },
        { status: "draft", currency: "USD", count: 34, totalAmount: 28517 },
        { status: "draft", currency: "AED", count: 22, totalAmount: 26679 },
        { status: "draft", currency: "QAR", count: 10, totalAmount: 6835 },
      ],
    },
    topOutstandingInvoices: [
      { customer: "Dcs Freight", openInvoices: 5, outstandingAed: 167185, oldestInvoice: "Oct 2025" },
      { customer: "Hilong", openInvoices: 3, outstandingAed: 129267, oldestInvoice: "Feb 2026" },
      { customer: "Al Faiq Readymade Garments", openInvoices: 5, outstandingAed: 98926, oldestInvoice: "Apr 2026" },
      { customer: "The One UAE", openInvoices: 6, outstandingAed: 95699, oldestInvoice: "Nov 2025" },
      { customer: "N0028 - Naser Al Sayer", openInvoices: 1, outstandingAed: 76276, oldestInvoice: "Mar 2026" },
      { customer: "Plethora General Trading", openInvoices: 1, outstandingAed: 51390, oldestInvoice: "Apr 2026" },
      { customer: "Final Specs Flooring", openInvoices: 2, outstandingAed: 50351, oldestInvoice: "Mar 2026" },
      { customer: "Lulu Supermarket", openInvoices: 5, outstandingAed: 48061, oldestInvoice: "Feb 2026" },
    ],
  },
  kpiPerformance: {
    periodLabel: "April 2026",
    periodTargets: [
      { id: "uuid-STA-APR-2026", code: "STA", name: "Sales Target Amount", period: "2026-04-01", target: 500000 },
      { id: "uuid-STE-APR-2026", code: "STE", name: "Sales Target Enquiries", period: "2026-04-01", target: 120 },
      { id: "uuid-NC-APR-2026", code: "NC", name: "New Customer", period: "2026-04-01", target: 10 },
      { id: "uuid-TJ-APR-2026", code: "TJ", name: "Total Jobs", period: "2026-04-01", target: 80 },
      { id: "uuid-GP-APR-2026", code: "GP", name: "Gross Profit", period: "2026-04-01", target: 75000 },
      { id: "uuid-SC-APR-2026", code: "SC", name: "Sales Collection", period: "2026-04-01", target: 300000 },
      { id: "uuid-ISJ-APR-2026", code: "ISJ", name: "Import Sea Jobs", period: "2026-04-01", target: 30 },
      { id: "uuid-ESJ-APR-2026", code: "ESJ", name: "Export Sea Jobs", period: "2026-04-01", target: 20 },
      { id: "uuid-ISC-APR-2026", code: "ISC", name: "Import Sea Containers", period: "2026-04-01", target: 60 },
      { id: "uuid-ESC-APR-2026", code: "ESC", name: "Export Sea Containers", period: "2026-04-01", target: 40 },
      { id: "uuid-AIJ-APR-2026", code: "AIJ", name: "Air Import Jobs", period: "2026-04-01", target: 15 },
      { id: "uuid-AEJ-APR-2026", code: "AEJ", name: "Air Export Jobs", period: "2026-04-01", target: 10 },
      { id: "uuid-AIT-APR-2026", code: "AIT", name: "Air Import Tons", period: "2026-04-01", target: 500 },
      { id: "uuid-AET-APR-2026", code: "AET", name: "Air Export Tons", period: "2026-04-01", target: 300 },
      { id: "uuid-OVL-APR-2026", code: "OVL", name: "Overland", period: "2026-04-01", target: 12 },
      { id: "uuid-WH-APR-2026", code: "WH", name: "Warehousing Jobs", period: "2026-04-01", target: 8 },
      { id: "uuid-PBB-APR-2026", code: "PBB", name: "Project / Breakbulk", period: "2026-04-01", target: 5 },
    ],
    periodActuals: [
      { id: "uuid-act-STA-APR-2026", targetId: "uuid-STA-APR-2026", actual: 319346.73, calculatedOn: "2026-04-22", source: "act_payment_receipt (AED)" },
      { id: "uuid-act-STE-APR-2026", targetId: "uuid-STE-APR-2026", actual: 96, calculatedOn: "2026-04-22", source: "crm_enquiry (Apr 2026)" },
      { id: "uuid-act-NC-APR-2026", targetId: "uuid-NC-APR-2026", actual: 7, calculatedOn: "2026-04-22", source: "crm_organization (Apr)" },
      { id: "uuid-act-TJ-APR-2026", targetId: "uuid-TJ-APR-2026", actual: 63, calculatedOn: "2026-04-22", source: "crm_job (Apr 2026)" },
      { id: "uuid-act-GP-APR-2026", targetId: "uuid-GP-APR-2026", actual: 41280, calculatedOn: "2026-04-22", source: "invoice (paid, Apr)" },
      { id: "uuid-act-SC-APR-2026", targetId: "uuid-SC-APR-2026", actual: 121007.26, calculatedOn: "2026-04-22", source: "act_payment_receipt.allocated" },
      { id: "uuid-act-ISJ-APR-2026", targetId: "uuid-ISJ-APR-2026", actual: 24, calculatedOn: "2026-04-22", source: "crm_sea_job (import, Apr)" },
      { id: "uuid-act-ESJ-APR-2026", targetId: "uuid-ESJ-APR-2026", actual: 18, calculatedOn: "2026-04-22", source: "crm_sea_job (export, Apr)" },
      { id: "uuid-act-ISC-APR-2026", targetId: "uuid-ISC-APR-2026", actual: 51, calculatedOn: "2026-04-22", source: "ops_container_details (import)" },
      { id: "uuid-act-ESC-APR-2026", targetId: "uuid-ESC-APR-2026", actual: 34, calculatedOn: "2026-04-22", source: "ops_container_details (export)" },
      { id: "uuid-act-AIJ-APR-2026", targetId: "uuid-AIJ-APR-2026", actual: 11, calculatedOn: "2026-04-22", source: "crm_air_job (import, Apr)" },
      { id: "uuid-act-AEJ-APR-2026", targetId: "uuid-AEJ-APR-2026", actual: 8, calculatedOn: "2026-04-22", source: "crm_air_job (export, Apr)" },
      { id: "uuid-act-AIT-APR-2026", targetId: "uuid-AIT-APR-2026", actual: 412, calculatedOn: "2026-04-22", source: "crm_air_job.total_gross_weight_kg" },
      { id: "uuid-act-AET-APR-2026", targetId: "uuid-AET-APR-2026", actual: 243, calculatedOn: "2026-04-22", source: "crm_air_job.total_gross_weight_kg" },
      { id: "uuid-act-OVL-APR-2026", targetId: "uuid-OVL-APR-2026", actual: 9, calculatedOn: "2026-04-22", source: "crm_road_job (Apr 2026)" },
      { id: "uuid-act-WH-APR-2026", targetId: "uuid-WH-APR-2026", actual: 5, calculatedOn: "2026-04-22", source: "crm_job (job_type=Warehouse)" },
      { id: "uuid-act-PBB-APR-2026", targetId: "uuid-PBB-APR-2026", actual: 3, calculatedOn: "2026-04-22", source: "crm_job (job_type=Project)" },
    ],
    comparisonRows: [
      { kpi: "Sales Target Amount", type: "Sales", unit: "AED", target: 500000, actual: 319347, achievement: 63.9, status: "red" },
      { kpi: "Sales Target Enquiries", type: "Sales", unit: "#", target: 120, actual: 96, achievement: 80, status: "yellow" },
      { kpi: "New Customer", type: "Sales", unit: "#", target: 10, actual: 7, achievement: 70, status: "yellow" },
      { kpi: "Total Jobs", type: "Operational", unit: "#", target: 80, actual: 63, achievement: 78.8, status: "yellow" },
      { kpi: "Gross Profit", type: "Financial", unit: "AED", target: 75000, actual: 41280, achievement: 55, status: "red" },
      { kpi: "Sales Collection", type: "Sales", unit: "AED", target: 300000, actual: 121007, achievement: 40.3, status: "red" },
      { kpi: "Import Sea Jobs", type: "Operational", unit: "#", target: 30, actual: 24, achievement: 80, status: "yellow" },
      { kpi: "Export Sea Jobs", type: "Operational", unit: "#", target: 20, actual: 18, achievement: 90, status: "green" },
      { kpi: "Import Sea Containers", type: "Operational", unit: "#", target: 60, actual: 51, achievement: 85, status: "yellow" },
      { kpi: "Export Sea Containers", type: "Operational", unit: "#", target: 40, actual: 34, achievement: 85, status: "yellow" },
      { kpi: "Air Import Jobs", type: "Operational", unit: "#", target: 15, actual: 11, achievement: 73.3, status: "yellow" },
      { kpi: "Air Export Jobs", type: "Operational", unit: "#", target: 10, actual: 8, achievement: 80, status: "yellow" },
      { kpi: "Air Import Tons", type: "Operational", unit: "tons", target: 500, actual: 412, achievement: 82.4, status: "yellow" },
      { kpi: "Air Export Tons", type: "Operational", unit: "tons", target: 300, actual: 243, achievement: 81, status: "yellow" },
      { kpi: "Overland", type: "Operational", unit: "#", target: 12, actual: 9, achievement: 75, status: "yellow" },
      { kpi: "Warehousing Jobs", type: "Operational", unit: "#", target: 8, actual: 5, achievement: 62.5, status: "red" },
      { kpi: "Project / Breakbulk", type: "Operational", unit: "#", target: 5, actual: 3, achievement: 60, status: "red" },
    ],
    thresholds: "Green >= 90% | Yellow 60-89% | Red < 60%",
  },
}

export const STEPS_CONFIG = [
  { id: 0, label: "Enquiry", count: 1521, icon: FileText },
  { id: 1, label: "Sub-Enquiry", count: 1520, icon: ClipboardList },
  { id: 2, label: "Jobs", count: 712, icon: Briefcase },
  { id: 3, label: "Operations", count: 666, icon: Activity },
  { id: 4, label: "POD", count: 39, icon: CheckCircle2 },
]
